version: "3.9"

services:
  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: laravel-php
    working_dir: /var/www/html
    user: root
    volumes:
      - ./src:/var/www/html:cached            # Laravel project code
      - laravel_storage:/var/www/html/storage # Named volume for storage
      - laravel_cache:/var/www/html/bootstrap/cache # Named volume only for cache
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      DB_SSL_MODE: DISABLED
    depends_on:
      - mysql
    networks:
      - laravel

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  # Nginx Web Server
  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:cached
    depends_on:
      - php
    networks:
      - laravel
  
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www.html

# Named Volumes
volumes:
  mysql_data:
  laravel_storage:
  laravel_cache:

# Network
networks:
  laravel:
    driver: bridge
